### PR TITLE
Posterity PR

### PR DESCRIPTION
**Pull request by steadysupply**
Preserving history for ETL spec module. History is aggressively filtered to remove any commits that didn't touch the files in this PR.

### CODE REVIEW

**Comment by steadysupply** [comment]
CircleCI seems to be failing on something unrelated:
```
AttributeError: module 'pydocstyle' has no attribute 'PEP257Checker'
```

**Comment by sdonk** [comment]
@steadysupply just merge latest develop to fix the issue

**Comment by steadysupply** [comment]
This PR is severely failing on `flake8`, but I would rather fix in the subsequent PR; that will make merging the two significantly easier .. ie. less than impossible.

I've used @bmcorser to assign @jim68000 to review .. once this is merged I can fix flake8 downstream.

**Comment by steadysupply** [comment]
Flake8 fails here are fixed in bcd822e
